{
 "title": "Dashboard trica",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, used_percent as mem_usage FROM mem WHERE time > now() - INTERVAL '1 hours' ORDER BY time DESC\r\n"
    }
   ]
  },
  {
   "title": "CPU Usage Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT time, 100.0 - usage_idle as cpu_usage FROM cpu WHERE time > now() - INTERVAL '1 hours' ORDER BY time DESC\r\n"
    }
   ]
  },
  {
   "title": " CPU Current (Jauge)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT 100.0 - usage_idle as cpu_usage FROM cpu WHERE cpu = 'cpu-total' ORDER BY time DESC LIMIT 1\r\n"
    }
   ]
  },
  {
   "title": "Memory Current (Jauge)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "iox",
     "rawSql": "SELECT used_percent as mem_usage FROM mem ORDER BY time DESC LIMIT 1\r\n"
    }
   ]
  }
 ]
}